## Resume Classification
### Business objective:
* **The document classification solution should significantly reduce the manual human effort in the HRM. It should achieve a higher level of accuracy and automation with minimal human intervention**

## 1. Import Library

In [5]:
pip install pip==24.0

Collecting pip==24.0
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 2.6 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 2.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1
    Uninstalling pip-25.1:
      Successfully uninstalled pip-25.1
Successfully installed pip-24.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
# pip install wordcloud
# pip install textract

Collecting wordcloudNote: you may need to restart the kernel to use updated packages.

  Downloading wordcloud-1.9.4-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.6.1 in c:\users\pc\anaconda3\lib\site-packages (from wordcloud) (2.1.3)
Requirement already satisfied: pillow in c:\users\pc\anaconda3\lib\site-packages (from wordcloud) (11.1.0)
Requirement already satisfied: matplotlib in c:\users\pc\anaconda3\lib\site-packages (from wordcloud) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pc\anaconda3\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\pc\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.12.0)
Downloading wordcloud-1.9.4-cp313-cp313-win_amd64.whl (300 kB)
   ---------------------------------------- 0.0/301.0 kB ? eta -:--:--
   -------------- ------------------------ 112.6/301.0 kB 34.5 MB/s eta 0:00:01
   ------------------------------- -------- 235.5/301.0 kB 3.2 MB/s eta 0:00:01
   ------------------------------- -------- 235.5/301.0 kB 3.2 MB/s eta 0:00:01
   ---------------------------------- ----- 256.0/301.0 kB 1.6 MB/s eta 0:00:01
   ---------------------------------------  297.0/301.0 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------  297.0/301.0 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------  297.0/301.0 kB 1.4 MB/s eta 0:00:01
   -------------------------------------- 301.0/301.0 kB 809.2 kB/s eta 0:00:00
Installing collected packages: wordcloud
Successfully installed wordcloud-1.9.4

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
import os
import re
import nltk
import spacy
import string
import textract
import pandas as pd
import seaborn as sns
from matplotlib import pylab
from matplotlib import pyplot as plt

from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from wordcloud import WordCloud, STOPWORDS
from nltk.stem import PorterStemmer, WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

import warnings
warnings.filterwarnings('ignore')

In [10]:
os.listdir(r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Datasets')

['Cleaned_Resumes (1).csv',
 'Cleaned_Resumes.csv',
 'Peoplesoft',
 'Raw_Resume1.csv',
 'React Developer',
 'Resumes',
 'skills.csv',
 'SQL Developer',
 'Test Resumes',
 'workday']

## 2. Exctract the Text from Dataset

# try to extract all folder one time
import os

file_name = []
category = []
base_dir = './Resume_Docx'
for root, dirs, files in os.walk(base_dir, topdown=False):
    for name in files:
        if name.endswith(".docx"):
            file_path = os.path.join(root, name)
            file_name.append(file_path)

In [11]:
file_path1 = []
category1  = []
directory1 = r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\PeopleSoft'
for i in os.listdir(directory1):
    if i.endswith('.docx'):
        os.path.join(directory1, i)
        file_path1.append((textract.process(os.path.join(directory1, i))).decode('utf-8'))
        category1.append('PeopleSoft')

In [12]:
data1 = pd.DataFrame(data = file_path1 , columns = ['Raw_Details'])
data1['Category1'] = category1
data1

                                          Raw_Details   Category1
0   Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...  PeopleSoft
1   G. Ananda Rayudu\n\n https://www.linkedin.com/...  PeopleSoft
2   PeopleSoft Database Administrator\n\n\n\nGanga...  PeopleSoft
3   Classification: Internal\n\nClassification: In...  PeopleSoft
4   Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...  PeopleSoft
5   SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...  PeopleSoft
6   PEOPLESOFT ADMINISTRATOR\n\n\n\n\n\nSRINIVAS.K...  PeopleSoft
7   PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...  PeopleSoft
8   Vinod Akkala PeopleSoft DBA Admin.\n\n\n\n\n\n...  PeopleSoft
9   PeopleSoft Admin/PeopleSoft DBA\n\n\n\nGanesh ...  PeopleSoft
10  PeopleSoft Administration\n\n \n\nVivekanand S...  PeopleSoft
11  Arun Venu\n\n\n\n\n\nEXPERIENCE SUMMARY\n\n\n\...  PeopleSoft
12  Personal Details\n\n\n\n\n\n\t\n\nExperience S...  PeopleSoft
13  Rahul Ahuja\n\n-------------------------------...  PeopleSoft
14  Hari Narayana \t\t              \n\n\t\n\n\n\n...  PeopleSoft
15  Murali\t\t       \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...  PeopleSoft
16  Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...  PeopleSoft
17  R Ahmed\tPeopleSoft Technical Consultant\n\n\n...  PeopleSoft
18  Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...  PeopleSoft
19  C O N T A C T :\n\n\n\nAddress: Manyata Tech P...  PeopleSoft

In [13]:
file_path2 = []
category2  = []
directory2 = r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\React Developer'
for i in os.listdir(directory2):
    if i.endswith('.docx'):
        os.path.join(directory2, i)
        file_path2.append((textract.process(os.path.join(directory2, i))).decode('utf-8'))
        category2.append('React JS Developer')

In [14]:
data2 = pd.DataFrame(data = file_path2 , columns = ['Raw_Details'])
data2['Category2'] = category2
data2

                                          Raw_Details           Category2
0   Name: Ravali P \n\n\n\n                       ...  React JS Developer
1   SUSOVAN  BAG   \n\nSeeking  a  challenging  po...  React JS Developer
2   Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...  React JS Developer
3   HARIPRIYA BATTINA \n\nExperience as UI Develop...  React JS Developer
4   KAMALAKAR REDDY. A \n\nLinked In: https://www....  React JS Developer
5   Naveen Sadhu\n\n\n\n\n\nTitle: software develo...  React JS Developer
6   Pavas\n\nGoswami\n\nFULLSTACK SOFTWARE DEVELOP...  React JS Developer
7   PRAGNYA PATTNAIK\n\n \n\n \n\n \n\n Expertise:...  React JS Developer
8   SARALA MADASU\n\nSARALA MADASU\n\n 204,Sri ge...  React JS Developer
9   Thirupathamma Balla\n\n\n\nSUMMARY:\n\n\n\n2.8...  React JS Developer
10  Maryala Vinay Reddy\n\n\n\n\tProfessional Summ...  React JS Developer
11  Ui-Developer/ React JS Developer \n\nNAME: KRI...  React JS Developer
12  Ui-Developer/ React JS Developer \n\nNAME: KRI...  React JS Developer
13  CURRICULUM VITAE\n\n\n\n\n\n\n\n\n\nAnjani\n\n...  React JS Developer
14  Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...  React JS Developer
15  Venkatalakshmi Pedireddy\n\nSoftware Developer...  React JS Developer
16  KAMBALA SAI SURENDRA   \n\n \n\n \n\n \n\n\n\n...  React JS Developer
17  MAREEDU LOKESH BABU\n\nPROFESSIONAL OVERVIEW\n...  React JS Developer
18  MAREEDU LOKESH BABU\n\n\n\nPROFESSIONAL OVERVI...  React JS Developer
19  MD KHIZARUDDIN RAUF \n\n \t EXPERIENCE \n\n   ...  React JS Developer
20  Name: M. Prabakaran\n\nTitle: UI Developer\n\n...  React JS Developer
21  Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...  React JS Developer
22  Ranga Gaganam  \n\n\n\n \n\nProfessional\n\n \...  React JS Developer
23  SHAIK ABDUL SHARUK   \n\n2 years’ Experience i...  React JS Developer

In [15]:
file_path3 = []
category3  = []
directory3 = r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\SQL Developer'
for i in os.listdir(directory3):
    if i.endswith('.docx'):
        os.path.join(directory3, i)
        file_path3.append((textract.process(os.path.join(directory3, i))).decode('utf-8'))
        category3.append('SQL Developer')

In [16]:
data3 = pd.DataFrame(data = file_path3 , columns = ['Raw_Details'])
data3['Category3'] = category3
data3

                                          Raw_Details      Category3
0   ANIL KUMAR MADDUKURI  \t\t\n\nSQL & MSBI Devel...  SQL Developer
1   Aradhana Tripathi\n\n\n\nCurrent Location: Gac...  SQL Developer
2   BUDDHA VAMSI                                  ...  SQL Developer
3   KAMBALLA PRADEEP                              ...  SQL Developer
4   Nazeer Basha\n\nSQL and Power BIDeveloper\n\n\...  SQL Developer
5   Resume\n\nName     :  Neeraj Mishra\n\n\n\nExp...  SQL Developer
6   SQL DEVELOPER\n\nName: -   Bandi prem sai\n\n\...  SQL Developer
7   SQL SERVER DEVELOPER\n\n\n\n\n\nPriyanka L\n\n...  SQL Developer
8   SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...  SQL Developer
9   RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...  SQL Developer
10  resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...  SQL Developer
11  Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...  SQL Developer
12  Tatikonda Kiran Kumar.\n\n\n\n\n\n\n\n\n\n\t C...  SQL Developer
13  SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...  SQL Developer

In [17]:
file_path4 = []
category4  = []
directory4 = r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\workday'
for i in os.listdir(directory4):
    if i.endswith('.docx'):
        os.path.join(directory4, i)
        file_path4.append((textract.process(os.path.join(directory4, i))).decode('utf-8'))
        category4.append('Workday')

In [18]:
data4 = pd.DataFrame(data = file_path4 , columns = ['Raw_Details'])
data4['Category4'] = category4
data4

                                          Raw_Details Category4
0   Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...   Workday
1   Name         : Gopi Krishna Reddy\n\n\t\t\t\t ...   Workday
2   Hari Krishna M\n\n\n\n\n\n\n\nSummary:\n\n\tA ...   Workday
3   Harikrishna Akula\n\n\n\n\n\n\n\nSummary:\n\n\...   Workday
4   HIMA.MENDU\n\n\n\n\n\nCareer Objective\n\nTo c...   Workday
5   G Himaja\n\n                                  ...   Workday
6   Name:  J. Sumanth Royal.\n\n\n\n\n\nPROFESSION...   Workday
7   JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...   Workday
8   Madeeswar A\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUM...   Workday
9   Mooraboyina Guravaiah\n\nWorkday Integration S...   Workday
10  Name  : Naresh Babu Cherukuri\n\n\n\n\n\nObjec...   Workday
11  VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...   Workday
12  Punugoti Swetha\n\nWorkday Technical Consultan...   Workday
13  Workday HCM  Techno functional Consultant     ...   Workday
14  Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...   Workday
15  Shireesh Balasani\n\nHCM Consultant\n\n\n\n\n\...   Workday
16  Workday Integration Consultant\n\n\n\n\tName\t...   Workday
17  Srikanth (WORKDAY hCM Consultant)\t           ...   Workday
18  WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...   Workday
19  Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...   Workday
20  Vinay kumar .v\nWorkday Functional Consultant\...   Workday

## 3. Create a DataFrame

In [20]:
import pandas as pd

resume_data = pd.concat([data1, data2, data3, data4], ignore_index=True)
resume_data

,Raw_Details,Category1,Category2,Category3,Category4
0,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,PeopleSoft,NaN,NaN,NaN
1,G. Ananda Rayudu\n\n https://www.linkedin.com/...,PeopleSoft,NaN,NaN,NaN
2,PeopleSoft Database Administrator\n\n\n\nGanga...,PeopleSoft,NaN,NaN,NaN
3,Classification: Internal\n\nClassification: In...,PeopleSoft,NaN,NaN,NaN
4,"Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...",PeopleSoft,NaN,NaN,NaN
...,...,...,...,...,...
74,Workday Integration Consultant\n\n\n\n\tName\t...,NaN,NaN,NaN,Workday
75,Srikanth (WORKDAY hCM Consultant)\t ...,NaN,NaN,NaN,Workday
76,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,NaN,NaN,NaN,Workday
77,Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...,NaN,NaN,NaN,Workday
78,Vinay kumar .v\nWorkday Functional Consultant\...,NaN,NaN,NaN,Workday

In [21]:
resume_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Raw_Details  79 non-null     object
 1   Category1    20 non-null     object
 2   Category2    24 non-null     object
 3   Category3    14 non-null     object
 4   Category4    21 non-null     object
dtypes: object(5)
memory usage: 3.2+ KB

### 3.1 Merge all Unnecessary column in One Column

In [22]:
resume_data['Category'] = category1 + category2 + category3 + category4
resume_data

,Raw_Details,Category1,Category2,Category3,Category4,Category
0,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
1,G. Ananda Rayudu\n\n https://www.linkedin.com/...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
2,PeopleSoft Database Administrator\n\n\n\nGanga...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
3,Classification: Internal\n\nClassification: In...,PeopleSoft,NaN,NaN,NaN,PeopleSoft
4,"Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...",PeopleSoft,NaN,NaN,NaN,PeopleSoft
...,...,...,...,...,...,...
74,Workday Integration Consultant\n\n\n\n\tName\t...,NaN,NaN,NaN,Workday,Workday
75,Srikanth (WORKDAY hCM Consultant)\t ...,NaN,NaN,NaN,Workday,Workday
76,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,NaN,NaN,NaN,Workday,Workday
77,Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...,NaN,NaN,NaN,Workday,Workday
78,Vinay kumar .v\nWorkday Functional Consultant\...,NaN,NaN,NaN,Workday,Workday

In [23]:
resume_data.drop(['Category1', 'Category2', 'Category3', 'Category4'], axis = 1, inplace = True)
resume_data = resume_data[["Category", "Raw_Details"]]

### 3.2 Final Dataset

In [24]:
resume_data.head(15)

      Category                                        Raw_Details
0   PeopleSoft  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...
1   PeopleSoft  G. Ananda Rayudu\n\n https://www.linkedin.com/...
2   PeopleSoft  PeopleSoft Database Administrator\n\n\n\nGanga...
3   PeopleSoft  Classification: Internal\n\nClassification: In...
4   PeopleSoft  Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...
5   PeopleSoft  SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n...
6   PeopleSoft  PEOPLESOFT ADMINISTRATOR\n\n\n\n\n\nSRINIVAS.K...
7   PeopleSoft  PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...
8   PeopleSoft  Vinod Akkala PeopleSoft DBA Admin.\n\n\n\n\n\n...
9   PeopleSoft  PeopleSoft Admin/PeopleSoft DBA\n\n\n\nGanesh ...
10  PeopleSoft  PeopleSoft Administration\n\n \n\nVivekanand S...
11  PeopleSoft  Arun Venu\n\n\n\n\n\nEXPERIENCE SUMMARY\n\n\n\...
12  PeopleSoft  Personal Details\n\n\n\n\n\n\t\n\nExperience S...
13  PeopleSoft  Rahul Ahuja\n\n-------------------------------...
14  PeopleSoft  Hari Narayana \t\t              \n\n\t\n\n\n\n...

In [25]:
resume_data["Raw_Details"][4]

'Priyanka Ramadoss\n\n\n\n61/46, MountPleasant, Coonoor\n\nThe Nilgiris- 643102\n\n\n\nCareer Objective\n\n\n\nTo excel as a software professional by working in a learning and challenging environment and utilize the skills and knowledge through diligence, dedication and ensure maximum contribution to the growth of the organization I work for.\n\n\n\nProfile Summary\n\n\n\nAn Adept IT professional with 4.11 years (September 2016 - present) of experience as Peoplesoft Admin with Accenture\n\n\n\nProfessional Summary\n\n\n\nPeopleSoft Administrator (September 2016-Present)\n\n\n\n\tExperience in PeopleSoft Administration for Finance application.\n\n\tProficient in creating and configuring PeopleSoft components like Web server, Application server and process schedulers.\n\n\tActive monitoring in Non production databases and applications.\n\n\tKnowledgeable on PeopleSoft migrations using application designer, data mover and taking compare reports and also moving the codes from DEV to TEST and production environments.\n\n\tUsage of HP PPM tool as well to perform PeopleSoft migrations and compare report generation.\n\n\tFull life cycle installation of PeopleSoft Environments.\n\n\tPre and Post database Refresh activities.\n\n\tChange package creation and applying bug fixes using change assistant to Peoplesoft DB.\n\n\tProficient in administration of Peoplesoft server components like application server, process scheduler, webserver. (Peoplesoft Internet Architecture)\n\n\tGood knowledge on basic PeopleSoft configurations like Integration Broker setup, PUM Setup, SSL and File attachments and trouble shooting them.\n\n\tHands on experience in Peoplesoft security level activities like creating user profile, assigning roles and permission list.\n\n\tSSO login creation for users by renewing web certificates.\n\n\tPerforming SOX checks and migrations as part of Production releases on monthly basis.\n\n\tConversant on the usage of Control-M V9 tool that is used for creating and scheduling the jobs.\n\n\tExperienced in setting up batch profile setup in server level for running control-m jobs in testing and production environments.\n\n\tPeoplesoft batch monitoring and implementation.\n\n\tWorked on Change Assistant.\n\n\tExperience in applying People tools patches.\n\n\tExperience in creating change packagees and target databases in CA and online.\n\n\tExperience in working in both Unix and Windows.\n\n\tWorked on Delphix virtual databases for non production database refreshes.\n\n\tCarrying out maintenance activities in servers.\n\n\n\n\tGood communication, Leadership abilities and problem solving skills.\n\n\n\n\tVMware ITBM Application Support Associate \t\n\n\n\n\tConfiguring and maintaining infrastructure for ITBM application in Windows OS.\n\n\tWorked on Apache Tomcat 7.0.39 and 7.0.52.\n\n\tVMware ITBM 80 and 82 versions on windows server.\n\n\tSSL configuration\n\n\tComplete batch setup in windows envrironment.\n\n\tHandling production and non production databases in ITBM\n\n\n\n\n\nTools and Technologies\n\n\n\nOperating Systems\n\n\t\uf0b7\tWindows 2007/2008/2012 server R2\n\n\tSolaris Server and Linux Red hat Version\n\n\tApache Tomcat 7.0.39 and 7.0.52\n\nAWS Service Tools\n\n\tCompute\n\n\tStorage\n\n\tNetworks\n\n\tDatabases\n\n\tMonitoring\n\n\tIdentity access management\n\nProject Management Tools\n\n\tOdyssey Dashboard\n\n\tOdyssey JIRA\n\n\tService Now\n\n\tTransporter\n\nDatabases\n\n\tSQL Developer\n\n\uf0b7\n\nPeopleSoft People Tools\n\n\t\uf0b7\t8.55.06\n\n\t\uf0b7\t8.55.22\n\n\t\uf0b7\t8.57\n\nPeopleSoft Application\n\nFSCM and 9.22 version\n\nReporting and PS Tools\n\n\tApplication Designer\n\n\tData Mover\n\n\tDelphix virtual database\n\n\tConfiguration Manager\n\n\tChange Assistant\n\n\tSQR, N-Vision,\n\n\tControl-M Scheduler\n\n\tHP PPM\n\n\tSQL developer\n\n\tCentrify Putty\n\n\tConfiguration manager\n\n\n\n\n\nKey Achievements :\n\n\n\n\tInfrastructure support for Production environments and also provide system contingency plans.\n\n\tAnalyze technical and functional aspects of the supported applications and troubleshoot problems based on requirements.\n\n\tDetailed Analysis and Reporting of Project activities.\n\n\n\nExperience Summary:\n\n\n\nOrganization : Accenture Solutions Pvt Ltd.\n\nClient : Credit - Suisse\n\nClient Description : Credit Suisse Group AG is a global wealth manager, investment bank and financial services company providing services in investment banking, provate banking and asset management and sahred services.\n\nResponsibility:  Environment administration and management for a financial application.\n\nLocation : Bangalore\n\nDuration : September 2016- Present\n\n\n\n\n\nEducation\n\n\n\n\n\nPercentage\n\n\n\nYear of passing\n\n\n\nBoard/University\n\n\n\nSchool/College\n\n\n\nCourse\n\n86%\n\n\n\n2016\n\n\n\nAnna University\n\nSri Krishna College of Engineering and Technology, Coimbatore\n\n\n\nB.E - ECE\n\n96.08%\n\nSchool Topper\n\n\n\n2012\n\nState Board of Technical Education\n\nBharathi Vidya Bhavan, Erode\n\n\n\nHSC\n\n93.8%\n\nDistrict Third\n\n\n\n2010\n\n\n\nAnglo-Indian\n\nSt. Joseph’s Convent Anglo Indian Girls Higher Secondary School, The Nilgiris\n\n\n\nS.S.L.C\n\n\n\nPersonal Profile\n\n\n\nPlace of birth\n\nOotacamund  (Ooty), Tamil Nadu district\n\n\n\n\n\nLanguages\n\nTamil – Native\n\nEnglish - Advanced- Comprehension - Oral Kannada - Intermediate – Oral\n\nHindi - Intermediate Sanskrit- Intermediate\n\nHobbies\n\nReading books, Yoga, Gardening, Surfing.'

### 3.3 Save new CSV File

In [27]:
resume_data.to_csv(r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\Raw_Resume1.csv', index=False)

## 4. Data Understanding

In [28]:
resume_data = pd.read_csv(r"C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\Raw_Resume1.csv")
resume_data

      Category                                        Raw_Details
0   PeopleSoft  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...
1   PeopleSoft  G. Ananda Rayudu\n\n https://www.linkedin.com/...
2   PeopleSoft  PeopleSoft Database Administrator\n\n\n\nGanga...
3   PeopleSoft  Classification: Internal\n\nClassification: In...
4   PeopleSoft  Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...
..         ...                                                ...
74     Workday  Workday Integration Consultant\n\n\n\n\tName\t...
75     Workday  Srikanth (WORKDAY hCM Consultant)\t           ...
76     Workday  WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...
77     Workday  Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...
78     Workday  Vinay kumar .v\nWorkday Functional Consultant\...

[79 rows x 2 columns]

In [29]:
resume_data[resume_data.Category == 'Workday']

   Category                                        Raw_Details
58  Workday  Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...
59  Workday  Name         : Gopi Krishna Reddy\n\n\t\t\t\t ...
60  Workday  Hari Krishna M\n\n\n\n\n\n\n\nSummary:\n\n\tA ...
61  Workday  Harikrishna Akula\n\n\n\n\n\n\n\nSummary:\n\n\...
62  Workday  HIMA.MENDU\n\n\n\n\n\nCareer Objective\n\nTo c...
63  Workday  G Himaja\n\n                                  ...
64  Workday  Name:  J. Sumanth Royal.\n\n\n\n\n\nPROFESSION...
65  Workday  JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...
66  Workday  Madeeswar A\n\n\n\n\n\n\n\n\n\n\n\nPROFILE SUM...
67  Workday  Mooraboyina Guravaiah\n\nWorkday Integration S...
68  Workday  Name  : Naresh Babu Cherukuri\n\n\n\n\n\nObjec...
69  Workday  VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...
70  Workday  Punugoti Swetha\n\nWorkday Technical Consultan...
71  Workday  Workday HCM  Techno functional Consultant     ...
72  Workday  Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
73  Workday  Shireesh Balasani\n\nHCM Consultant\n\n\n\n\n\...
74  Workday  Workday Integration Consultant\n\n\n\n\tName\t...
75  Workday  Srikanth (WORKDAY hCM Consultant)\t           ...
76  Workday  WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...
77  Workday  Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...
78  Workday  Vinay kumar .v\nWorkday Functional Consultant\...

In [30]:
resume_data.isnull().sum()

Category       0
Raw_Details    0
dtype: int64

### 4.1 Number of Words in each Resume

In [31]:
resume_data['Word_Count'] = resume_data['Raw_Details'].apply(lambda x: len(str(x).split(" ")))
resume_data[['Raw_Details','Word_Count']].head()

                                         Raw_Details  Word_Count
0  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...        1023
1  G. Ananda Rayudu\n\n https://www.linkedin.com/...         825
2  PeopleSoft Database Administrator\n\n\n\nGanga...         738
3  Classification: Internal\n\nClassification: In...         558
4  Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...         541

### 4.2 Number of Characters

In [32]:
resume_data['Char_Count'] = resume_data['Raw_Details'].str.len() ## this also includes spaces
resume_data[['Raw_Details','Char_Count']].head()

                                         Raw_Details  Char_Count
0  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...        8010
1  G. Ananda Rayudu\n\n https://www.linkedin.com/...        7646
2  PeopleSoft Database Administrator\n\n\n\nGanga...        6104
3  Classification: Internal\n\nClassification: In...        4917
4  Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...        5102

### 4.3 Number of Stopwords

In [33]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
resume_data['Stopwords'] = resume_data['Raw_Details'].apply(lambda x: len([x for x in x.split() if x in stop]))
resume_data[['Raw_Details','Stopwords']].head()

                                         Raw_Details  Stopwords
0  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...        190
1  G. Ananda Rayudu\n\n https://www.linkedin.com/...        186
2  PeopleSoft Database Administrator\n\n\n\nGanga...        177
3  Classification: Internal\n\nClassification: In...        114
4  Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...        123

### 4.4 Number of Numerics

In [34]:
resume_data['Numerics'] = resume_data['Raw_Details'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
resume_data[['Raw_Details','Numerics']].head()

                                         Raw_Details  Numerics
0  Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...         4
1  G. Ananda Rayudu\n\n https://www.linkedin.com/...         6
2  PeopleSoft Database Administrator\n\n\n\nGanga...         4
3  Classification: Internal\n\nClassification: In...         7
4  Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...         7

In [35]:
resume_data

,Category,Raw_Details,Word_Count,Char_Count,Stopwords,Numerics
0,PeopleSoft,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,1023,8010,190,4
1,PeopleSoft,G. Ananda Rayudu\n\n https://www.linkedin.com/...,825,7646,186,6
2,PeopleSoft,PeopleSoft Database Administrator\n\n\n\nGanga...,738,6104,177,4
3,PeopleSoft,Classification: Internal\n\nClassification: In...,558,4917,114,7
4,PeopleSoft,"Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...",541,5102,123,7
...,...,...,...,...,...,...
74,Workday,Workday Integration Consultant\n\n\n\n\tName\t...,888,7094,197,3
75,Workday,Srikanth (WORKDAY hCM Consultant)\t ...,1063,6737,194,9
76,Workday,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,1076,8329,236,6
77,Workday,Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...,877,6630,193,7
78,Workday,Vinay kumar .v\nWorkday Functional Consultant\...,702,5126,150,2

## 5. Text Pre-Processing

### 5.1 Using Regular Expression

In [36]:
def preprocess(sentence):
    sentence = str(sentence)
    sentence = sentence.lower()
    sentence = sentence.replace('{html}',"") 
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', sentence)
    rem_url = re.sub(r'http\S+', '',cleantext)
    rem_num = re.sub('[0-9]+', '', rem_url)
    tokenizer = RegexpTokenizer(r'\w+')
    tokens = tokenizer.tokenize(rem_num)  
    filtered_words = [w for w in tokens if len(w) > 2 if not w in stopwords.words('english')]

    return " ".join(filtered_words)

In [39]:
resume_data = pd.read_csv(r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\Raw_Resume1.csv')
resume_data['Resume_Details'] = resume_data.Raw_Details.apply(lambda x: preprocess(x))

### 5.2 Clean Text from Resume

In [40]:
resume_data

,Category,Raw_Details,Resume_Details
0,PeopleSoft,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...,anubhav kumar singh core competencies scriptin...
1,PeopleSoft,G. Ananda Rayudu\n\n https://www.linkedin.com/...,ananda rayudu profile summary years experience...
2,PeopleSoft,PeopleSoft Database Administrator\n\n\n\nGanga...,peoplesoft database administrator gangareddy p...
3,PeopleSoft,Classification: Internal\n\nClassification: In...,classification internal classification interna...
4,PeopleSoft,"Priyanka Ramadoss\n\n\n\n61/46, MountPleasant,...",priyanka ramadoss mountpleasant coonoor nilgir...
...,...,...,...
74,Workday,Workday Integration Consultant\n\n\n\n\tName\t...,workday integration consultant name sri krishn...
75,Workday,Srikanth (WORKDAY hCM Consultant)\t ...,srikanth workday hcm consultant seeking suitab...
76,Workday,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...,workday hcm fcm name kumar role workday consul...
77,Workday,Venkateswarlu.B\tWorkday Consultant\n\n\n\n\n\...,venkateswarlu workday consultant years experie...
78,Workday,Vinay kumar .v\nWorkday Functional Consultant\...,vinay kumar workday functional consultant expe...

### 5.3 Save the Clean Data in new CSV File

In [41]:
resume_data.drop(['Raw_Details'], axis = 1, inplace = True)
resume_data

      Category                                     Resume_Details
0   PeopleSoft  anubhav kumar singh core competencies scriptin...
1   PeopleSoft  ananda rayudu profile summary years experience...
2   PeopleSoft  peoplesoft database administrator gangareddy p...
3   PeopleSoft  classification internal classification interna...
4   PeopleSoft  priyanka ramadoss mountpleasant coonoor nilgir...
..         ...                                                ...
74     Workday  workday integration consultant name sri krishn...
75     Workday  srikanth workday hcm consultant seeking suitab...
76     Workday  workday hcm fcm name kumar role workday consul...
77     Workday  venkateswarlu workday consultant years experie...
78     Workday  vinay kumar workday functional consultant expe...

[79 rows x 2 columns]

In [42]:
resume_data.to_csv(r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\Cleaned_Resumes.csv', index = False)

In [44]:
resume_data = pd.read_csv(r'C:\Users\PC\Downloads\Data Science\Project2\Final-Code-Project2\Resume_Classification_project\Datasets\Resumes\Cleaned_Resumes.csv')
resume_data

      Category                                     Resume_Details
0   PeopleSoft  anubhav kumar singh core competencies scriptin...
1   PeopleSoft  ananda rayudu profile summary years experience...
2   PeopleSoft  peoplesoft database administrator gangareddy p...
3   PeopleSoft  classification internal classification interna...
4   PeopleSoft  priyanka ramadoss mountpleasant coonoor nilgir...
..         ...                                                ...
74     Workday  workday integration consultant name sri krishn...
75     Workday  srikanth workday hcm consultant seeking suitab...
76     Workday  workday hcm fcm name kumar role workday consul...
77     Workday  venkateswarlu workday consultant years experie...
78     Workday  vinay kumar workday functional consultant expe...

[79 rows x 2 columns]

In [45]:
resume_data.Resume_Details[5]

'sirazuddin bangalore india sirazuddin bangalore india profile summary overall years experience peoplesoft administrator installed peopletools scratch including products experience peopletools application hrms fscm deterministic approach towards problem solving troubleshooting proficient integration broker upgraded fscm hcm applications peopletools peopletools education graduated tech electronics communication engg college engineering vizianagaram jntuk aggregate achieved marks standard scored standard achievements awarded bravo pat back techahindra awarded associate month award innovator month time awarded spot pat back capgemini work experience capgemini may till production support finance environment respective non production environments project experience project name axa role consultant environment windows server cognizant technol ogy sol ions augus april voya financial insurance client project deals support managing finance applications project experience project name voya financials role associate environment windows server tech mahindra limit july augus peoplesoft implemented fin application peoplesoft implementation project includes peoplesoft applications interfaces third party applications interfaces live production peoplesoft environment sdlc project experience project name role environment cio common software engineer solaris windows server responsibilities provided administrative supports peoplesoft tools version application hrms financials scm modules windows unix creation indexes tables application designer peoplesoft database setup troubleshooting issues daily peoplesoft admin activities configured peoplesoft application server process scheduler web server domains setup master scheduler installing oracle tuxedo weblogic java application disk fscm hcm oracle database unix windows servers scratch installed peopletools hcm fscm demo database upgraded fscm application peopletools peopletools applied patch fscm configured report nodes bouncing app web process schedulers clearing cache performed pre refresh post refresh activity database cloning activity recompilation cobol source codes worked project migrations using application designer change assistant applied image fscm using pum change assistant good hands experience application designer data mover change assistant well aware pia peoplesoft internet architecture configuring integration broker report nodes creating udm file transfer interfaces monitoring deploying gnupg keys certificates servers installed configured elastic search tools used peopletools application designer data mover toad sqldeveloper microsoft sql management studio oracle oracle microsoft sql server filezilla winscp pcomm tws service silva training certifications oracle cloud infrastructure architect associate oracle cloud infrastructure architect professional'

# THE END !!!